### ISSUE TITLE
Notification message always shown

### ISSUE THREAD

**Issue by matvey-kazakov** [NEERC/chat-android#1]
Can we show notification only when it has valuable information?

**Comment by mityada** [comment]
Since b6f2f13 notification is only shown when user is logged in.

The purpose of this notification is to show user that the chat is running. It also reflects presence and amount of new tasks. Some other useful information like contest clock can be added later.

**Comment by matvey-kazakov** [comment]
I've got number of chat applications: Hangouts, Telegram, What's Up, Skype, Allo... All of them accept new messages and show notifications upon updates only. My understanding is that it should done in one of the ways:
- Show when some activity happens (like last message, number of new messages / tasks, etc.) and ability to swipe it out
- Continuous items like contest clock or something else should be configurable. In apps that do that there is an option - "show ... in notifications".
Otherwise it is too annoying
